package com.aro.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class client_info implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Client Phone Number")
	private Integer client_phone;

	@org.kie.api.definition.type.Label(value = "Client Email Address")
	private java.lang.String client_email;

	@org.kie.api.definition.type.Label(value = "Client Name")
	private java.lang.String client_name;

	@org.kie.api.definition.type.Label(value = "Address")
	private java.lang.String client_address;

	@org.kie.api.definition.type.Label(value = "Social Security Number")
	private java.lang.Integer client_ssn;

	public client_info() {
	}

	public java.lang.Integer getClient_phone() {
		return this.client_phone;
	}

	public void setClient_phone(java.lang.Integer client_phone) {
		this.client_phone = client_phone;
	}

	public java.lang.String getClient_email() {
		return this.client_email;
	}

	public void setClient_email(java.lang.String client_email) {
		this.client_email = client_email;
	}

	public java.lang.String getClient_name() {
		return this.client_name;
	}

	public void setClient_name(java.lang.String client_name) {
		this.client_name = client_name;
	}

	public java.lang.String getClient_address() {
		return this.client_address;
	}

	public void setClient_address(java.lang.String client_address) {
		this.client_address = client_address;
	}

	public java.lang.Integer getClient_ssn() {
		return this.client_ssn;
	}

	public void setClient_ssn(java.lang.Integer client_ssn) {
		this.client_ssn = client_ssn;
	}

	public client_info(java.lang.Integer client_phone,
			java.lang.String client_email, java.lang.String client_name,
			java.lang.String client_address, java.lang.Integer client_ssn) {
		this.client_phone = client_phone;
		this.client_email = client_email;
		this.client_name = client_name;
		this.client_address = client_address;
		this.client_ssn = client_ssn;
	}

}